"""Add Device and TelemetryLog Models

Revision ID: dec48b0fc855
Revises: b42bb88b516c
Create Date: 2026-03-09 08:04:28.189600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec48b0fc855'
down_revision: Union[str, None] = 'b42bb88b516c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('is_stolen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('battery', sa.Integer(), nullable=False),
    sa.Column('network_type', sa.String(), nullable=False),
    sa.Column('trigger_source', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_logs_device_id'), 'telemetry_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_latitude'), 'telemetry_logs', ['latitude'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_longitude'), 'telemetry_logs', ['longitude'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_logs_longitude'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_latitude'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_device_id'), table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    op.drop_table('devices')
    # ### end Alembic commands ###
